### ISSUE TITLE
UI: Admin Dashboard for App Metrics

### ISSUE THREAD

**Issue by schmelz21** [cisagov/XFD#27]
# 💡 Summary #

Create an admin application dashboard that reports application metrics for system admins. The dashboard metrics should include: 
- **User Data Metrics**: Display key metrics related to user activity, such as sign-ups, logins, and active users. 
- **Organization Data Metrics**: Show relevant data about organizations, such as the number of organizations, their size, and engagement levels. 
- **Scans Metrics**: Present information related to security scans, performance, frequency, and/or any other relevant scans conducted within the application.

Secondarily all reportable data should allow for "csv, excel" exports.

## Motivation and context ##

This is invaluable tool to manage service reports. 

## Implementation notes ##
[ ] Gather desired metrics from Stakeholders
[ ] Create Wireframe/Proposal for Dashboard Design
[ ] Add total number of registered users.
[ ] Add daily active users (DAU) and monthly active users (MAU).
[ ] Add User engagement metrics (e.g., average session duration, most visited pages).
[ ] Add total number of organizations.
[ ] Add Distribution of organization sizes (small, medium, large).
[ ] Add Metrics related to organization activity (e.g., number of projects, collaboration frequency).
[ ] Add Performance scan metrics (e.g., response time, resource utilization).

## Acceptance criteria ##
- [ ] Document all end-point changes
- [ ]  Demonstrate a Response Design
- [ ] Include Screenshots Of Updated Views
- [ ] Commit to Staging
- [ ] Create Functional Tests
